package com.gusedu.model;
// Generated 01/03/2016 03:47:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CabeceraFactura generated by hbm2java
 */
public class CabeceraFactura  implements java.io.Serializable {


     private Integer codFactura;
     private String cliente;
     private Double monto;
     private Date fecha;
     private String facturaReal;
     private Integer codCliente;
     private Integer estado;
     private Integer codVisita;
     private Set detalleFacturas = new HashSet(0);

    public CabeceraFactura() {
    }

    public CabeceraFactura(String cliente, Double monto, Date fecha, String facturaReal, Integer codCliente, Integer estado, Integer codVisita, Set detalleFacturas) {
       this.cliente = cliente;
       this.monto = monto;
       this.fecha = fecha;
       this.facturaReal = facturaReal;
       this.codCliente = codCliente;
       this.estado = estado;
       this.codVisita = codVisita;
       this.detalleFacturas = detalleFacturas;
    }
   
    public Integer getCodFactura() {
        return this.codFactura;
    }
    
    public void setCodFactura(Integer codFactura) {
        this.codFactura = codFactura;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getFacturaReal() {
        return this.facturaReal;
    }
    
    public void setFacturaReal(String facturaReal) {
        this.facturaReal = facturaReal;
    }
    public Integer getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(Integer codCliente) {
        this.codCliente = codCliente;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Integer getCodVisita() {
        return this.codVisita;
    }
    
    public void setCodVisita(Integer codVisita) {
        this.codVisita = codVisita;
    }
    public Set getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


