package com.gusedu.model;
// Generated 01/03/2016 03:47:23 PM by Hibernate Tools 4.3.1



/**
 * EnfermedadPar generated by hbm2java
 */
public class EnfermedadPar  implements java.io.Serializable {


     private Integer expCodigo;
     private Enfermedad enfermedad;
     private Par par;
     private String expDescripcion;

    public EnfermedadPar() {
    }

	
    public EnfermedadPar(Enfermedad enfermedad, Par par) {
        this.enfermedad = enfermedad;
        this.par = par;
    }
    public EnfermedadPar(Enfermedad enfermedad, Par par, String expDescripcion) {
       this.enfermedad = enfermedad;
       this.par = par;
       this.expDescripcion = expDescripcion;
    }
   
    public Integer getExpCodigo() {
        return this.expCodigo;
    }
    
    public void setExpCodigo(Integer expCodigo) {
        this.expCodigo = expCodigo;
    }
    public Enfermedad getEnfermedad() {
        return this.enfermedad;
    }
    
    public void setEnfermedad(Enfermedad enfermedad) {
        this.enfermedad = enfermedad;
    }
    public Par getPar() {
        return this.par;
    }
    
    public void setPar(Par par) {
        this.par = par;
    }
    public String getExpDescripcion() {
        return this.expDescripcion;
    }
    
    public void setExpDescripcion(String expDescripcion) {
        this.expDescripcion = expDescripcion;
    }




}


