package com.gusedu.model;
// Generated 01/03/2016 03:47:23 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Logueo generated by hbm2java
 */
public class Logueo  implements java.io.Serializable {


     private Integer idLogueo;
     private String usuario;
     private String empresa;
     private Date fecha;

    public Logueo() {
    }

    public Logueo(String usuario, String empresa, Date fecha) {
       this.usuario = usuario;
       this.empresa = empresa;
       this.fecha = fecha;
    }
   
    public Integer getIdLogueo() {
        return this.idLogueo;
    }
    
    public void setIdLogueo(Integer idLogueo) {
        this.idLogueo = idLogueo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


