package com.gusedu.model;
// Generated 01/03/2016 03:47:23 PM by Hibernate Tools 4.3.1



/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private Integer pagoCodigo;
     private TipoPago tipoPago;
     private CabeceraFactura factura;
     private Double monto;

    public Pago() {
    }

    public Pago(Integer pagoCodigo, TipoPago tipoPago, CabeceraFactura factura, Double monto) {
        this.pagoCodigo = pagoCodigo;
        this.tipoPago = tipoPago;
        this.factura = factura;
        this.monto = monto;
    }
   
    public Integer getPagoCodigo() {
        return this.pagoCodigo;
    }
    
    public void setPagoCodigo(Integer pagoCodigo) {
        this.pagoCodigo = pagoCodigo;
    }
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }

    public CabeceraFactura getFactura() {
        return factura;
    }

    public void setFactura(CabeceraFactura factura) {
        this.factura = factura;
    }

    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }




}


